source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'


platform :ios, '8.0'
use_frameworks!

target ‘Vestorly’ do
    pod 'SwiftyJSON', '~> 2.2.1'
end


platform :ios, ‘8.0’
xcodeproj ‘Vestorly.xcodeproj'
pod 'AFNetworking', '~> 2.1'
pod 'JSONModel', '~> 1.0'
pod 'ISO8601'